search_text = "robot"
search_field = "gh-ac"
search_button = "gh-btn"
item = "//ul[contains(@class,'srp-results')]//li[contains(@class, 's-item')]"
dropdown_button = "//span[@aria-labelledby='srp-ipp-label-text']//button[contains(@class, 'fake-menu-button__button')]"
first_button_of_dropdown = "//div[@id='s0-14-11-6-3-SEARCH_PAGINATION_MODEL_V2-answer-23-2-3-content-menu']/a[1]"
