search_field = "//input[@name='search']"
search_button = "//button[@class='b7j']"
item_xpath = "//div[@class='a0c6']"
add_to_wishlist_button = "//div[@class='_29hd _3hUf _1KAI']"
wishlist_link = "//a[@href='/my/favorites']"
